"""add rating, reputation and activeness to user

Revision ID: 1b7d75149dd4
Revises: 8d4b6770fbf3
Create Date: 2020-08-24 08:50:48.713724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7d75149dd4'
down_revision = '8d4b6770fbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activeness', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('reputation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reputation')
    op.drop_column('user', 'rating')
    op.drop_column('user', 'activeness')
    # ### end Alembic commands ###
