"""add bmi to patient

Revision ID: 976209a51e44
Revises: cd282fa04718
Create Date: 2020-08-22 09:40:05.713672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976209a51e44'
down_revision = 'cd282fa04718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('bmi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'bmi')
    # ### end Alembic commands ###
