"""fix models

Revision ID: cd282fa04718
Revises: cea108f7f3e1
Create Date: 2020-08-20 12:07:32.065950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd282fa04718'
down_revision = 'cea108f7f3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_creme_model_name'), 'creme_model', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creme_model_name'), table_name='creme_model')
    # ### end Alembic commands ###
